# Generated by Django 6.0 on 2025-12-14 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca_modelo', models.CharField(max_length=100)),
                ('año', models.IntegerField()),
                ('kilometraje', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
                ('combustible', models.CharField(choices=[('nafta', 'Nafta'), ('diesel', 'Diésel'), ('hibrido', 'Híbrido'), ('electrico', 'Eléctrico')], max_length=20)),
                ('transmision', models.CharField(choices=[('manual', 'Manual'), ('automatica', 'Automática')], max_length=20)),
                ('estado_general', models.TextField()),
                ('mantenimiento', models.TextField()),
                ('documentacion', models.TextField()),
                ('ubicacion', models.CharField(max_length=100)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FotoCoche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='coches/')),
                ('coche', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app.coche')),
            ],
        ),
    ]
